apiVersion: v1
kind: Pod
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  containers:
  - name: mongo
    image: mongo:4.4
    ports:
      - containerPort: 27017
    volumeMounts:
      - mountPath: /data/db
        name: mongo-storage
  volumes:
    - name: mongo-storage
      persistentVolumeClaim:
        claimName: spring-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    app: mongo
  ports:
  - port: 27017
    targetPort: 27017
  type: ClusterIP
