apiVersion: v1
kind: PersistentVolume
metadata: 
  name: spring-pv
  labels:
    pv: spring-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  # claimRef:
  #   name: spring-pvc
  nfs:
    server: 192.168.56.13
    path: /mnt/nfs_share 