apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spring-pvc
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  selector:
    matchLabels:
      pv: spring-pv
