
apiVersion: v1
kind: ConfigMap
metadata:
  name: tomcat-config
data:
    tomcat-users.xml: |
      <?xml version="1.0" encoding="UTF-8"?>

      <tomcat-users xmlns="http://tomcat.apache.org/xml"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://tomcat.apache.org/xml tomcat-users.xsd"
              version="1.0">

      <user username="tomcat" password="tomcat"
      roles="manager-gui,admin-gui,manager-script,manager-jmx,manager-status,admin-script,admin,manager,host-manager"/>
  
      </tomcat-users>
      
    manager-META-INF-context.xml: |
      <?xml version="1.0" encoding="UTF-8"?>

      <Context antiResourceLocking="false" privileged="true" ignoreAnnotations="true">
        <CookieProcessor className="org.apache.tomcat.util.http.Rfc6265CookieProcessor"
                         sameSiteCookies="strict" />
        <!-- <Valve className="org.apache.catalina.valves.RemoteAddrValve"
               allow="127\.\d+\.\d+\.\d+|::1|0:0:0:0:0:0:0:1" /> -->
        <Manager sessionAttributeValueClassNameFilter="java\.lang\.(?:Boolean|Integer|Long|Number|String)|org\.apache\.catalina\.filters\.CsrfPreventionFilter\$LruCache(?:\$1)?|java\.util\.(?:Linked)?HashMap"/>
      </Context>
      
    host-manager-META-INF-context.xml: |
      <?xml version="1.0" encoding="UTF-8"?>

      <Context antiResourceLocking="false" privileged="true" ignoreAnnotations="true">
        <CookieProcessor className="org.apache.tomcat.util.http.Rfc6265CookieProcessor"
                         sameSiteCookies="strict" />
      <!--  <Valve className="org.apache.catalina.valves.RemoteAddrValve"
         allow="127\.\d+\.\d+\.\d+|::1|0:0:0:0:0:0:0:1" /> -->
      <Manager sessionAttributeValueClassNameFilter="java\.lang\.(?:Boolean|Integer|Long|Number|String)|org\.apache\.catalina\.filters\.CsrfPreventionFilter\$LruCache(?:\$1)?|java\.util\.(?:Linked)?HashMap"/>