apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-mongo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-mongo
  template:
    metadata:
      labels:
        app: spring-mongo
    spec:
      containers:
      - name: spring-mongo
        image: deepaksag/mongo-spring:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: docker
        - name: MANAGEMENT_HEALTH_RABBIT_ENABLED
          value: "false"
        - name: MANAGEMENT_HEALTH_MEMCACHED_ENABLED
          value: "false"
        - name: SPRING_DATA_MONGODB_URI
          value: mongodb://mongo-svc:27017/devopsdb
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 3


--- 
apiVersion: v1
kind: Service
metadata:
  name: spring-mongo-svc
  namespace: default
spec:
  selector:
    app: spring-mongo
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer