apiVersion: v1
kind: Pod
metadata:
  name: node-affinty
  labels:
    app: nodelabel
spec:
  containers:
    - name: node-affinity
      image: nginx
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution: 
        nodeSelectorTerms:
          - matchExpressions: 
              - key: node
                operator: In
                values:
                  - slow
  
  