apiVersion: apps/v1
kind: Deployment
metadata: 
  name: affinity-node
  namespace: default

spec:
  replicas: 2
  selector:
    matchLabels:
      pod: affi-po
  template:
    metadata:
      labels:
         pod: affi-po
    spec:
      # restartPolicy: Always
      containers:
      - name: cont-01
        image: nginx
        imagePullPolicy: IfNotPresent
        command: ["sh", "-c"]
        args: ["while true; do echo hello; sleep 10;done"]
        ports:
        - containerPort: 8080
        # resources:
        #   limits:
        #     cpu: 500m
        #     memory: 500Mi
        #   requests: 
        #     cpu: 200m
        #     memory: 200Mi
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #         - matchExpressions:
      #             - key: node
      #               operator: In
      #               values:
      #               - worker1

      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                    - worker2