apiVersion: apps/v1
kind: Deployment
metadata: 
  name: node-selector
  namespace: default

spec:
  replicas: 2
  selector:
    matchLabels:
      pod: affi-po
  template:
    metadata:
      labels:
         pod: affi-po
    spec:
      # restartPolicy: Always
      containers:
      - name: cont-01
        image: nginx
        imagePullPolicy: IfNotPresent
        command: ["sh", "-c"]
        args: ["while true; do echo hello; sleep 10;done"]
        ports:
        - containerPort: 8080
        # resources:
        #   limits:
        #     cpu: 500m
        #     memory: 500Mi
        #   requests: 
        #     cpu: 200m
        #     memory: 200Mi
        
      nodeSelector:
        kubernetes.io/hostname: worker1