apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: sandboxed
handler: runc
overhead:
  podFixed:
    cpu: "100m"
    memory: "128Mi"

---

apiVersion: v1
kind: Pod
metadata:
  name: secure-pod
spec:
  runtimeClassName: sandboxed
  containers:
  - name: app
    image: nginx
    resources:
      requests:
        cpu: "200m"
        memory: "200Mi"
