apiVersion: v1
kind: Pod
metadata:
  name: pod01
  namespace: practice
  labels:
    app: app01
spec:
  containers:
  - name: app01
    image: nginx
    resources:
      limits:
        cpu: 200m
        memory: 600Mi
      requests: 
        cpu: 200m
        memory: 500Mi
  - name: app02
    image: nginx
    resources:
      limits:
        cpu: 200m
        memory: 600Mi
      requests: 
        cpu: 200m
        memory: 500Mi
  - name: app03
    image: nginx
    resources:
      limits:
        cpu: 200m
        memory: 600Mi
      requests: 
        cpu: 200m
        memory: 500Mi