apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
  - name: myapp
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    env:
      # - name: username
      #   valueFrom:
      #     secretKeyRef:
      #       name: test-secret
      #       key: username
      # - name: password
      #   valueFrom:
      #     secretKeyRef:
      #       name: test-secret
      #       key: password
      - name: key1
        valueFrom:
          secretKeyRef:
            name: test-secret
            key: key1
      - name: key2
        valueFrom:
          secretKeyRef:
            name: test-secret
            key: key2

    volumeMounts:
      - name: secret-volume
        mountPath: /etc/secret-volume
        readOnly: true
  volumes:
    - name: secret-volume
      secret:
        secretName: test-secret
        items:
          - key: key1
            path: key1
          - key: key2
            path: key2
          # - key: username
          #   path: username
          # - key: password
          #   path: password


