# kubectl create secret docker-registry regcred \
# --docker-server=https://hub.docker.com/repositories/deepaksag \
# --docker-username=deepaksag \
# --docker-password=<your-pwd> \
# --docker-email=<your-email>

apiVersion: v1
kind: Pod
metadata:
  name: private-image-pod
  labels:
    app: private-image-pod
spec:
  containers:
    - name: private-image-container
      image: deepaksag/java-webapp:latest
      ports:
        - containerPort: 8080
  imagePullSecrets:
    - name: regcred

--- 
apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  selector:
    app: private-image-pod
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30081
  type: NodePort
